### ISSUE TITLE
Wrong variable name, 1 underscore instead of 2

### ISSUE THREAD

**Issue by dtourde** [francois09/ansible_role_hass#7]
https://github.com/francois09/ansible_role_hass/blob/2e30752ff98b6e8adc5261ae7415e77bd6882107/tasks/main.yml#L77
https://github.com/francois09/ansible_role_hass/blob/2e30752ff98b6e8adc5261ae7415e77bd6882107/tasks/main.yml#L89

**Comment by francois09** [comment]
Good catch ! Thx ;)
